services:
  minecraftbedrock:
    build: .
    container_name: minecraftbedrock
    ports:
      - "${PORT:-19132}:19132/udp"
    volumes:
      - server:/data/server
    environment:
      - SEED=${SEED:-abc}
    restart: unless-stopped

volumes:
  server: